version: '3'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_CONNECTION: "postgres://postgres:postgres@db/postgres"
      REDIS_HOST: "redis"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - .env
